"""Registration token model for HomelabCmd.

This model represents one-time registration tokens for pull-based agent installation.
Tokens are generated by the hub and claimed by agents during installation.
"""

from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from homelab_cmd.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from homelab_cmd.db.models.server import Server


class AgentMode(str, Enum):
    """Operating mode for agents."""

    READONLY = "readonly"
    READWRITE = "readwrite"


class RegistrationToken(TimestampMixin, Base):
    """SQLAlchemy model for agent registration tokens.

    Registration tokens are one-time use tokens generated by the hub for
    pull-based agent installation. Users copy a curl command containing
    the token, run it on the target server, and the agent claims the
    token to receive its credentials.

    Attributes:
        id: Auto-increment primary key
        token_hash: SHA-256 hash of the full token (we never store plaintext)
        token_prefix: First 8 chars of token for display (e.g., "hlh_rt_a")
        mode: Agent operating mode (readonly/readwrite)
        display_name: Optional human-readable name for the server
        monitored_services: JSON array of systemd services to monitor
        expires_at: When the token expires (default: 15 minutes from creation)
        claimed_at: Timestamp when token was claimed (null if unclaimed)
        claimed_by_server_id: Server ID that claimed this token
        created_at: Record creation timestamp
        updated_at: Record update timestamp
    """

    __tablename__ = "registration_tokens"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Token storage (hash only, never plaintext)
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    token_prefix: Mapped[str] = mapped_column(String(16), nullable=False)

    # Pre-configured settings for the agent
    mode: Mapped[str] = mapped_column(
        String(20),
        default=AgentMode.READONLY.value,
        nullable=False,
    )
    display_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    monitored_services: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Token lifecycle
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    claimed_by_server_id: Mapped[str | None] = mapped_column(
        String(100),
        ForeignKey("servers.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Relationship to server (optional, set when claimed)
    claimed_by_server: Mapped["Server | None"] = relationship(
        "Server",
        foreign_keys=[claimed_by_server_id],
        lazy="select",
    )

    @property
    def is_expired(self) -> bool:
        """Check if the token has expired."""
        from datetime import UTC

        now = datetime.now(UTC)
        expires = self.expires_at

        # Handle timezone-naive datetimes (e.g., from SQLite)
        if expires.tzinfo is None:
            # Assume UTC for naive datetimes
            now = now.replace(tzinfo=None)

        return now > expires

    @property
    def is_claimed(self) -> bool:
        """Check if the token has been claimed."""
        return self.claimed_at is not None

    @property
    def is_valid(self) -> bool:
        """Check if the token is valid (not expired and not claimed)."""
        return not self.is_expired and not self.is_claimed

    def __repr__(self) -> str:
        """Return string representation of the token."""
        status = "claimed" if self.is_claimed else ("expired" if self.is_expired else "valid")
        return f"<RegistrationToken(id={self.id}, prefix={self.token_prefix!r}, status={status})>"
