"""Add remediation_actions table

Revision ID: 0ff25fb760c4
Revises: c3d4e5f6g7h8
Create Date: 2026-01-19 15:36:01.617957

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ff25fb760c4'
down_revision: str | Sequence[str] | None = 'c3d4e5f6g7h8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.create_index('idx_remediation_actions_server_status', ['server_id', 'status'], unique=False)
        batch_op.create_index('idx_remediation_actions_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediation_actions_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_actions_server_id'))
        batch_op.drop_index('idx_remediation_actions_status')
        batch_op.drop_index('idx_remediation_actions_server_status')

    op.drop_table('remediation_actions')
    # ### end Alembic commands ###
