"""extend_remediation_actions_schema

Revision ID: 471db12d81d1
Revises: 0ff25fb760c4
Create Date: 2026-01-19 17:49:30.417249

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '471db12d81d1'
down_revision: str | Sequence[str] | None = '0ff25fb760c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('exit_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stdout', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stderr', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_remediation_actions_alert_id', 'alerts', ['alert_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_remediation_actions_alert_id', type_='foreignkey')
        batch_op.drop_column('stderr')
        batch_op.drop_column('stdout')
        batch_op.drop_column('exit_code')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('executed_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('alert_id')

    # ### end Alembic commands ###
