#!/bin/bash
# HomelabCmd Agent Installation Script
#
# This script installs the homelab-agent on a Linux server.
# It must be run as root.
#
# Usage:
#   sudo ./install.sh                      # Interactive install (prompts for config)
#   sudo ./install.sh --mode readonly      # Install read-only agent (monitoring only)
#   sudo ./install.sh --mode readwrite     # Install read/write agent (full management)
#   sudo ./install.sh --remote             # Unattended install (config pre-deployed)
#   sudo ./install.sh --remote --mode readwrite  # Remote with specific mode
#   sudo ./install.sh --token hlh_rt_xxx --hub-url http://hub:8080  # Pull-based install
#
# Operating Modes (BG0017):
#   readonly  - Metrics collection only, maximum security hardening
#               Runs as dedicated 'homelab-agent' user
#               Cannot execute any commands
#
#   readwrite - Full management including command execution
#               Runs as root
#               Can execute whitelisted commands (apt-get, systemctl, etc.)
#
# Pull-Based Installation:
#   Use --token with a registration token generated by the hub. This claims the
#   token to receive per-agent credentials and configuration. The mode and
#   other settings are pre-configured in the token.
#
# The script will:
#   1. Create /opt/homelab-agent/ and copy the agent script
#   2. Install Python dependencies (psutil, httpx, pyyaml)
#   3. Create /etc/homelab-agent/ for configuration
#   4. Create homelab-agent user (for readonly mode)
#   5. Install the appropriate systemd service
#   6. Enable the service (but not start it, unless --remote or --token)
#
# After installation, edit /etc/homelab-agent/config.yaml with your settings,
# then start the service with: systemctl start homelab-agent

set -e

# Parse arguments
REMOTE_MODE=false
AGENT_MODE=""  # Will be set to "readonly" or "readwrite"
REGISTRATION_TOKEN=""  # Pull-based installation token
HUB_URL=""  # Hub URL for pull-based installation
SERVER_ID=""  # Optional server ID override

while [[ $# -gt 0 ]]; do
    case $1 in
        --remote)
            REMOTE_MODE=true
            shift
            ;;
        --mode)
            AGENT_MODE="$2"
            shift 2
            ;;
        --mode=*)
            AGENT_MODE="${1#*=}"
            shift
            ;;
        --token)
            REGISTRATION_TOKEN="$2"
            shift 2
            ;;
        --token=*)
            REGISTRATION_TOKEN="${1#*=}"
            shift
            ;;
        --hub-url)
            HUB_URL="$2"
            shift 2
            ;;
        --hub-url=*)
            HUB_URL="${1#*=}"
            shift
            ;;
        --server-id)
            SERVER_ID="$2"
            shift 2
            ;;
        --server-id=*)
            SERVER_ID="${1#*=}"
            shift
            ;;
        -h|--help)
            echo "Usage: ./install.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --mode readonly    Install read-only agent (monitoring only)"
            echo "  --mode readwrite   Install read/write agent (full management)"
            echo "  --remote           Unattended install (config pre-deployed)"
            echo "  --token TOKEN      Registration token for pull-based install"
            echo "  --hub-url URL      Hub URL (required with --token)"
            echo "  --server-id ID     Server identifier (optional, derived from hostname)"
            echo "  -h, --help         Show this help message"
            echo ""
            echo "If --mode is not specified, you will be prompted to choose."
            echo "Use --token for pull-based installation from the hub."
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: ./install.sh [--mode readonly|readwrite] [--remote] [--token TOKEN --hub-url URL]"
            exit 1
            ;;
    esac
done

# Validate pull-based installation arguments
if [[ -n "$REGISTRATION_TOKEN" && -z "$HUB_URL" ]]; then
    echo -e "${RED:-}Error: --hub-url is required when using --token${NC:-}"
    exit 1
fi

# Colours for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

# Check for root
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root${NC}"
    echo "Usage: sudo ./install.sh"
    exit 1
fi

AGENT_DIR="/opt/homelab-agent"
CONFIG_DIR="/etc/homelab-agent"
SERVICE_FILE="/etc/systemd/system/homelab-agent.service"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Prompt for mode if not specified (skip for pull-based installation)
if [[ -z "$AGENT_MODE" && -z "$REGISTRATION_TOKEN" ]]; then
    echo ""
    echo -e "${CYAN}Select agent operating mode:${NC}"
    echo ""
    echo "  1) readonly  - Metrics collection only (recommended for most users)"
    echo "                 Maximum security, runs as unprivileged user"
    echo "                 Cannot execute commands on the server"
    echo ""
    echo "  2) readwrite - Full management capabilities"
    echo "                 Runs as root, can execute whitelisted commands"
    echo "                 Required for: package updates, service restarts"
    echo ""
    read -p "Enter choice [1/2] (default: 1): " MODE_CHOICE

    case "$MODE_CHOICE" in
        2|readwrite)
            AGENT_MODE="readwrite"
            ;;
        *)
            AGENT_MODE="readonly"
            ;;
    esac
fi

# Validate mode (skip for pull-based installation - mode comes from token)
if [[ -z "$REGISTRATION_TOKEN" ]]; then
    if [[ "$AGENT_MODE" != "readonly" && "$AGENT_MODE" != "readwrite" ]]; then
        echo -e "${RED}Error: Invalid mode '$AGENT_MODE'. Must be 'readonly' or 'readwrite'${NC}"
        exit 1
    fi
    echo ""
    echo -e "${GREEN}Installing homelab-agent in ${CYAN}${AGENT_MODE}${GREEN} mode...${NC}"
else
    echo ""
    echo -e "${GREEN}Installing homelab-agent with pull-based registration...${NC}"
fi

# Create directories
echo "Creating directories..."
mkdir -p "$AGENT_DIR"
mkdir -p "$CONFIG_DIR"

# Create homelab-agent user (for both modes, runs as unprivileged user)
if ! id -u homelab-agent &>/dev/null; then
    echo "Creating homelab-agent user..."
    useradd --system --no-create-home --shell /usr/sbin/nologin homelab-agent
fi

# Ensure config directory is readable by the agent user
chown root:homelab-agent "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"

# Configure sudo for readwrite mode (skip for pull-based - handled after token claim)
SUDOERS_FILE="/etc/sudoers.d/homelab-agent"
if [[ "$AGENT_MODE" == "readwrite" && -z "$REGISTRATION_TOKEN" ]]; then
    echo "Configuring sudo permissions for readwrite mode..."
    cat > "$SUDOERS_FILE" << 'EOF'
# HomelabCmd Agent - Passwordless sudo for whitelisted commands (BG0017)
# This file is auto-generated by install.sh --mode readwrite
#
# Commands are also whitelisted in the agent code (defence in depth)

# Allow apt-get commands for package management
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get update
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get upgrade -y
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get install *

# Allow systemctl restart for service management
homelab-agent ALL=(root) NOPASSWD: /usr/bin/systemctl restart *

# Allow journalctl vacuum for log management
homelab-agent ALL=(root) NOPASSWD: /usr/bin/journalctl --vacuum-time=*
EOF
    chmod 440 "$SUDOERS_FILE"
    # Validate sudoers syntax
    if ! visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
        echo -e "${RED}Error: Invalid sudoers file generated${NC}"
        rm -f "$SUDOERS_FILE"
        exit 1
    fi
    echo -e "${GREEN}Sudo permissions configured${NC}"
elif [[ -z "$REGISTRATION_TOKEN" ]]; then
    # Remove sudoers file if switching to readonly mode (not in pull-based mode)
    if [[ -f "$SUDOERS_FILE" ]]; then
        echo "Removing sudo permissions (readonly mode)..."
        rm -f "$SUDOERS_FILE"
    fi
fi

# Copy agent package (skip if already in place - remote deploy extracts directly)
if [[ "$SCRIPT_DIR" != "$AGENT_DIR" ]]; then
    echo "Copying agent package..."
    cp "$SCRIPT_DIR/__init__.py" "$AGENT_DIR/"
    cp "$SCRIPT_DIR/__main__.py" "$AGENT_DIR/"
    cp "$SCRIPT_DIR/config.py" "$AGENT_DIR/"
    cp "$SCRIPT_DIR/collectors.py" "$AGENT_DIR/"
    cp "$SCRIPT_DIR/heartbeat.py" "$AGENT_DIR/"
    # Copy executor.py if it exists (for readwrite mode)
    if [[ -f "$SCRIPT_DIR/executor.py" ]]; then
        cp "$SCRIPT_DIR/executor.py" "$AGENT_DIR/"
    fi
    # Copy VERSION if it exists
    if [[ -f "$SCRIPT_DIR/VERSION" ]]; then
        cp "$SCRIPT_DIR/VERSION" "$AGENT_DIR/"
    fi
else
    echo "Agent files already in place..."
fi
chmod 644 "$AGENT_DIR/"*.py

# Check for Python 3
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 is required but not installed${NC}"
    echo "Install Python 3 with: apt install python3 python3-pip"
    exit 1
fi

# Install Python dependencies
echo "Installing Python dependencies..."
# Prefer apt packages (works on modern Debian/Ubuntu with PEP 668)
if apt-get install -y python3-psutil python3-httpx python3-yaml 2>/dev/null; then
    echo "Installed dependencies via apt"
elif command -v pip3 &> /dev/null; then
    # Try pip with --break-system-packages for older systems
    pip3 install --quiet --break-system-packages psutil httpx pyyaml 2>/dev/null || \
    pip3 install --quiet psutil httpx pyyaml || {
        echo -e "${RED}Error: Could not install Python dependencies${NC}"
        exit 1
    }
else
    echo -e "${RED}Error: Could not install Python dependencies${NC}"
    echo "Install with: apt install python3-psutil python3-httpx python3-yaml"
    exit 1
fi

# Copy the appropriate systemd service file
echo "Installing systemd service (${AGENT_MODE} mode)..."
if [[ "$AGENT_MODE" == "readonly" ]]; then
    SERVICE_SOURCE="$SCRIPT_DIR/homelab-agent-readonly.service"
else
    SERVICE_SOURCE="$SCRIPT_DIR/homelab-agent-readwrite.service"
fi

# Fall back to generic service file if mode-specific doesn't exist
if [[ ! -f "$SERVICE_SOURCE" ]]; then
    SERVICE_SOURCE="$SCRIPT_DIR/homelab-agent.service"
fi

cp "$SERVICE_SOURCE" "$SERVICE_FILE"

# Handle configuration
if [[ -n "$REGISTRATION_TOKEN" ]]; then
    # Pull-based installation: claim token from hub
    echo "Claiming registration token from hub..."

    # Derive server_id from hostname if not provided
    if [[ -z "$SERVER_ID" ]]; then
        SERVER_ID=$(hostname | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
        if [[ -z "$SERVER_ID" ]]; then
            SERVER_ID="server-$(date +%s)"
        fi
    fi

    HOSTNAME=$(hostname)

    # Claim the token
    CLAIM_RESPONSE=$(curl -sSL -X POST "${HUB_URL}/api/v1/agents/register/claim" \
        -H "Content-Type: application/json" \
        -d "{\"token\": \"$REGISTRATION_TOKEN\", \"server_id\": \"$SERVER_ID\", \"hostname\": \"$HOSTNAME\"}" 2>&1) || {
        echo -e "${RED}Error: Failed to connect to hub at ${HUB_URL}${NC}"
        echo "$CLAIM_RESPONSE"
        exit 1
    }

    # Check if claim was successful
    if echo "$CLAIM_RESPONSE" | grep -q '"success":false'; then
        ERROR=$(echo "$CLAIM_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('error', 'Unknown error'))" 2>/dev/null || echo "Token claim failed")
        echo -e "${RED}Error: Token claim failed - $ERROR${NC}"
        exit 1
    fi

    # Extract configuration from response
    CONFIG_YAML=$(echo "$CLAIM_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('config_yaml', ''))" 2>/dev/null) || {
        echo -e "${RED}Error: Failed to parse claim response${NC}"
        echo "$CLAIM_RESPONSE"
        exit 1
    }

    if [[ -z "$CONFIG_YAML" ]]; then
        echo -e "${RED}Error: No configuration received from hub${NC}"
        exit 1
    fi

    echo -e "${GREEN}Token claimed successfully!${NC}"

    # Write configuration
    echo "$CONFIG_YAML" > "$CONFIG_DIR/config.yaml"

    # Extract mode from config
    AGENT_MODE=$(echo "$CONFIG_YAML" | grep "^mode:" | awk '{print $2}' || echo "readonly")

    # Set appropriate permissions
    if [[ "$AGENT_MODE" == "readonly" ]]; then
        chown root:homelab-agent "$CONFIG_DIR/config.yaml"
        chmod 640 "$CONFIG_DIR/config.yaml"
    else
        chmod 600 "$CONFIG_DIR/config.yaml"
    fi

    CONFIG_CREATED=false
    REMOTE_MODE=true  # Treat as remote mode from here (auto-start)

    # Configure sudo for readwrite mode (may have been skipped due to unknown mode earlier)
    if [[ "$AGENT_MODE" == "readwrite" ]]; then
        if [[ ! -f "$SUDOERS_FILE" ]]; then
            echo "Configuring sudo permissions for readwrite mode..."
            cat > "$SUDOERS_FILE" << 'EOF'
# HomelabCmd Agent - Passwordless sudo for whitelisted commands (BG0017)
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get update
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get upgrade -y
homelab-agent ALL=(root) NOPASSWD: /usr/bin/apt-get install *
homelab-agent ALL=(root) NOPASSWD: /usr/bin/systemctl restart *
homelab-agent ALL=(root) NOPASSWD: /usr/bin/journalctl --vacuum-time=*
EOF
            chmod 440 "$SUDOERS_FILE"
            if ! visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
                echo -e "${YELLOW}Warning: Could not configure sudo permissions${NC}"
                rm -f "$SUDOERS_FILE"
            fi
        fi
    fi

elif [[ "$REMOTE_MODE" == true ]]; then
    # In remote mode, config.yaml should already be deployed
    if [[ ! -f "$CONFIG_DIR/config.yaml" ]]; then
        echo -e "${RED}Error: config.yaml not found in $CONFIG_DIR${NC}"
        echo "Remote mode requires config to be pre-deployed"
        exit 1
    fi
    CONFIG_CREATED=false

    # Update config with mode if not already set
    if ! grep -q "^mode:" "$CONFIG_DIR/config.yaml"; then
        echo "mode: $AGENT_MODE" >> "$CONFIG_DIR/config.yaml"
    fi
else
    # Create config from template if it doesn't exist
    if [[ ! -f "$CONFIG_DIR/config.yaml" ]]; then
        if [[ -f "$SCRIPT_DIR/config.yaml.example" ]]; then
            cp "$SCRIPT_DIR/config.yaml.example" "$CONFIG_DIR/config.yaml"
        else
            # Create minimal config template
            cat > "$CONFIG_DIR/config.yaml" << EOF
# HomelabCmd Agent Configuration
#
# Operating mode: readonly or readwrite (BG0017)
# - readonly:  Metrics only, no command execution
# - readwrite: Full management, can execute commands
mode: $AGENT_MODE

# Hub connection
hub_url: http://your-hub-server:8080
server_id: $(hostname)
api_key: YOUR_API_KEY_HERE

# Heartbeat interval in seconds
heartbeat_interval: 60

# Services to monitor (optional)
# monitored_services:
#   - nginx
#   - docker

# Command execution settings (only used in readwrite mode)
command_execution:
  enabled: true
  use_sudo: false
  timeout_seconds: 30
EOF
        fi
        chmod 600 "$CONFIG_DIR/config.yaml"

        # Set ownership for readonly mode
        if [[ "$AGENT_MODE" == "readonly" ]]; then
            chown root:homelab-agent "$CONFIG_DIR/config.yaml"
            chmod 640 "$CONFIG_DIR/config.yaml"
        fi

        echo -e "${YELLOW}Created configuration template at $CONFIG_DIR/config.yaml${NC}"
        CONFIG_CREATED=true
    else
        echo "Configuration file already exists at $CONFIG_DIR/config.yaml"
        CONFIG_CREATED=false

        # Update mode in existing config if needed
        if ! grep -q "^mode:" "$CONFIG_DIR/config.yaml"; then
            # Add mode line after hub_url or at start of file
            sed -i "1i mode: $AGENT_MODE" "$CONFIG_DIR/config.yaml"
            echo -e "${YELLOW}Added mode: $AGENT_MODE to existing config${NC}"
        fi
    fi
fi

# Reload systemd
echo "Reloading systemd..."
systemctl daemon-reload

# Enable service
systemctl enable homelab-agent

# In remote mode, start the service automatically
if [[ "$REMOTE_MODE" == true ]]; then
    echo "Starting homelab-agent service..."
    systemctl start homelab-agent
    echo -e "${GREEN}Installation complete - agent started in ${CYAN}${AGENT_MODE}${GREEN} mode${NC}"
else
    echo ""
    echo -e "${GREEN}Installation complete!${NC}"
    echo ""
    echo -e "Agent mode: ${CYAN}${AGENT_MODE}${NC}"

    if [[ "$AGENT_MODE" == "readonly" ]]; then
        echo "  - Metrics collection only"
        echo "  - Running as unprivileged 'homelab-agent' user"
        echo "  - Cannot execute commands"
    else
        echo "  - Full management capabilities"
        echo "  - Running as root"
        echo "  - Can execute whitelisted commands"
    fi
    echo ""

    if [[ "$CONFIG_CREATED" == true ]]; then
        echo -e "${YELLOW}Next steps:${NC}"
        echo "1. Edit $CONFIG_DIR/config.yaml with your settings:"
        echo "   - Set hub_url to your HomelabCmd server address"
        echo "   - Set server_id to a unique identifier for this server"
        echo "   - Set api_key to match your hub's HOMELAB_CMD_API_KEY"
        echo ""
        echo "2. Start the service:"
        echo "   systemctl start homelab-agent"
        echo ""
    else
        echo "Start the service with:"
        echo "   systemctl start homelab-agent"
        echo ""
    fi

    echo "Other useful commands:"
    echo "   systemctl status homelab-agent    # Check service status"
    echo "   journalctl -u homelab-agent -f    # View live logs"
    echo "   systemctl restart homelab-agent   # Restart after config changes"
    echo ""
    echo "To change mode, reinstall with:"
    echo "   sudo ./install.sh --mode <readonly|readwrite>"
fi
